# version: "3.3"
# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#   redis:
#     image: "redis:alpine"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}